version: '3'
services:
  integration_node:
    build:
      context: .
      dockerfile: integrations/node.Dockerfile
    command: "npx jest __tests__/integration.test.js"
    environment:
      - HTTPBIN=true
      - INTEGRATION_CLIENT=node
