version: '3'
services:
  httpbin:
    image: kennethreitz/httpbin
  httpsnippet:
    build: .
    command: "npx mocha test/requests.js"
    environment:
      - HTTPBIN
    depends_on:
      - httpbin
