version: '3'
services:
  integration_node:
    build:
      context: .
      dockerfile: integrations/node.Dockerfile
    command: "npx jest src/integration.test.ts"
    environment:
      - HTTPBIN=true
      - INTEGRATION_CLIENT=node
      - NODE_ENV=integration

  integration_php:
    build:
      context: .
      dockerfile: integrations/php.Dockerfile
    command: "npx jest src/integration.test.ts"
    environment:
      - HTTPBIN=true
      - INTEGRATION_CLIENT=php
      - NODE_ENV=integration

  integration_python:
    build:
      context: .
      dockerfile: integrations/python.Dockerfile
    command: "npx jest src/integration.test.ts"
    environment:
      - HTTPBIN=true
      - INTEGRATION_CLIENT=python
      - NODE_ENV=integration

  integration_shell:
    build:
      context: .
      dockerfile: integrations/shell.Dockerfile
    command: "npx jest src/integration.test.ts"
    environment:
      - HTTPBIN=true
      - INTEGRATION_CLIENT=shell
      - NODE_ENV=integration
