version: '3'
services:
  integration_node:
    build:
      context: .
      dockerfile: integrations/node.Dockerfile
    command: "npx jest __tests__/integration.test.js"
    environment:
      - HTTPBIN=true
      - INTEGRATION_CLIENT=node

  integration_php:
    build:
      context: .
      dockerfile: integrations/php.Dockerfile
    command: "npx jest __tests__/integration.test.js"
    environment:
      - HTTPBIN=true
      - INTEGRATION_CLIENT=php

  integration_python:
    build:
      context: .
      dockerfile: integrations/python.Dockerfile
    command: "npx jest __tests__/integration.test.js"
    environment:
      - HTTPBIN=true
      - INTEGRATION_CLIENT=python

  integration_shell:
    build:
      context: .
      dockerfile: integrations/shell.Dockerfile
    command: "npx jest __tests__/integration.test.js"
    environment:
      - HTTPBIN=true
      - INTEGRATION_CLIENT=shell
