version: '3'
services:
  httpbin:
    image: kennethreitz/httpbin
  integration_node:
    build:
      context: .
      dockerfile: node.Dockerfile
    command: "npx jest __tests__/integration.test.js"
    environment:
      - HTTPBIN=true
      - INTEGRATION_CLIENT=node
    depends_on:
      - httpbin
