name: Integrations (Go)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: docker-compose run integration_golang

      - name: Cleanup
        if: always()
        run: docker-compose down
